# Site settings
title: "Jeff's Blog"
email: "fossj117@gmail.com"
description: "This is the future home of Jeff's blog."
baseurl: ""
url: "" # the base hostname & protocol for your site
twitter_username: "jfoss117"
github_username:  "fossj117"

# Build settings
markdown: kramdown

BASE_PATH: "/Users/jeffreyfossett/Files/blog"