# Site settings
title: "Jeff's Blog"
email: "fossj117@gmail.com"
description: "This is the future home of Jeff's blog."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: "jfoss117"
github_username:  "fossj117"

# Build settings
markdown: kramdown
