# Site settings
title: "Jeff Fossett"
email: "fossj117@gmail.com"
description: "Trying things out"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jeffreyfossett.com" # the base hostname & protocol for your site
twitter_username: "jfoss117"
github_username: "fossj117"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false
